import ErrorPage from "./404Page/404Page";
import LoginPage from "./LoginPage/LoginPage";
import ForgotPassword from "./ForgotPassword/ForgotPassword";
import ProfileProfile from "./ProfileProfile/ProfileProfile";
import LoginEmailTemplate from "./LoginEmailTemplate/LoginEmailTemplate";
import ProfileProfileAbout from "./ProfileProfileAbout/ProfileProfileAbout";
import TutorCompleteProfile from "./TutorCompleteProfile/TutorCompleteProfile";
import TutorDashboardLoadingScreen from "./TutorDashboardLoadingScreen/TutorDashboardLoadingScreen";
import ProfileProfileAdditionalDetails from "./ProfileProfileAdditionalDetails/ProfileProfileAdditionalDetails";
import TutorDashboardLoadingScreenMobile from "./TutorDashboardLoadingScreenMobile/TutorDashboardLoadingScreenMobile";

export {
    ErrorPage,
    LoginPage,
    ForgotPassword,
    ProfileProfile,
    LoginEmailTemplate,
    ProfileProfileAbout,
    TutorCompleteProfile,
    TutorDashboardLoadingScreen,
    ProfileProfileAdditionalDetails,
    TutorDashboardLoadingScreenMobile,
};